### ISSUE TITLE
ip.icmp.payload just loops back to ip

### ISSUE THREAD

**Issue by irl** [nevil-brownlee/python-libtrace#2]
When attempting to view the payload of an ICMP message, you just get the original IP packet back, not the one in the quotation.

```
ip == ip.icmp.payload == ip.icmp.payload.icmp.payload
```

**Comment by irl** [comment]
I may well have no idea what I'm talking about, but it looks like line 203 of icmp.c is just returning a copy of the packet, not a new packet containing the quotation.

https://github.com/nevil-brownlee/python-libtrace/blob/master/lib/plt/icmp.c#L203

**Comment by irl** [comment]
As a workaround, you can do:

```
quotation = libtrace.ip(ip.icmp.data[8:])
```

This is sub-optimal however.

**Comment by nevil-brownlee** [comment]
The line you pointed to above in icmp.c was the right place to look.  The code simply failed to return a bytearray for ICMP types it didn't recognise, and the test programs didn't test for that.
This is fixed in my changes to icmp.py, icmp6.py in the v2- and v3-test-cases, and in the .html doc files for ICMP and ICMP6.

Thanks for the feedback, Nevil
